management:
  endpoint:
    health:
      show-details: always

config:
  mongodb:
    uri: mongodb+srv://diegosauriio:Tommy123@diegosauriio.9lwluyu.mongodb.net/?retryWrites=true&w=majority
    database: Diegosauriio