#====== connect to postgreSQL ======#
spring:
  #datasource:
  #  url: ${DATASOURCE_URL}
  #  username: ${DATASOURCE_USER}
  #  password: ${DATASOURCE_PASSWORD}
  #jpa:
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.PostgreSQLDialect
  #      # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
  #      temp:
   #       use_jdbc_metadata_defaults: false
    # Because detection is disabled you have to set correct dialect by hand.
  #  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#====== connect to mongo ======#
  data:
    mongodb:
      uri: mongodb+srv://diegosauriio:Tommy123@diegosauriio.9lwluyu.mongodb.net/?retryWrites=true&w=majority
      database: Diegosauriio